FROM node:20-slim

WORKDIR /usr/src/friezz

COPY package*.json .
COPY turbo.json .
COPY tsconfig.json .
COPY .env.development .env

COPY ./apps/client ./apps/client
COPY ./apps/common ./apps/common

RUN npm install

RUN npm run build -- --scope='common' --include-dependencies --no-deps