version: '3.8'

services:
  database_postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env.development
    volumes:
      - ./database/friezz_db_schema.sql:/docker-entrypoint-initdb.d/friezz_db_schema.sql
    ports:
      - "5432:5432"
    expose:
      - 5432

  tool_pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env.development
    ports:
      - "5050:80"
    depends_on:
      - database_postgres