version: '3'

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./friezz_schema.sql:/docker-entrypoint-initdb.d/friezz_schema.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=letmein
    ports:
      - "5432:5432"
    expose:
      - 5432

  # liquibase:
  #   image: liquibase/liquibase:latest
  #   volumes:
  #     - ./changelog.yaml:/liquibase/changelog.yaml
  #   depends_on:
  #     - postgres
  #   command: --url=jdbc:postgresql://postgres:5432/postgres --username=postgres --password=letmein --changeLogFile=./changelog.yaml update

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@example.com
      - PGADMIN_DEFAULT_USERNAME=postgres
      - PGADMIN_DEFAULT_PASSWORD=letmein
    ports:
      - "5050:80"
    depends_on:
      - postgres
