export const DEFAULT_QUESTIONS: { [lang: string]: string[] } = {
    en: [
        'What would you do with 20 million?',
        "What's your dream trip?",
        "Who's your first crush?",
        'Which celebrity would you have dinner with, alive or dead?',
        "What's your secret treat?",
        'What superpower would you like to have?',
        "What's your favorite food?",
        "What's your favorite band?",
        "What's your favorite color?",
        "What's your cutest mistake?",
        'What was your biggest pain?',
        "What's your favorite food?",
        "What's your favorite drink?",
        "What's the thing you're most ashamed of?",

        'What would be your RPG character (warrior, mage, paladin, thief...)?',
        'First action if you become master of the world?',
    ],
    fr: [
        "Qu'est ce que tu fais avec 20 millions ?",
        'Quel est ton voyage de rêve ?',
        'Qui est ton premier crush ?',
        'Avec quel célébrité tu irai dinner vivante ou morte ?',
        'Quel est ton petit plaisir secret ?',
        'Quel super pouvoir tu voudrai avoir ?',
        'Quel est ton plat préféré ?',
        'Quel est ton groupe préféré ?',
        'Quel est ta couleur préférée ?',
        'Quelle est ta plus jolie bêtise ?',
        'Quelle a été ta plus grosse douleur ?',
        'Quel est ton plat préféré ?',
        'Quelle est ta boisson préférée ?',
        'Quelle est la chose dont tu as le plus honte ?',
        'Quel est ta madeleine de Proust ?',

        'Quel serait ton personnage de JDR (guerrier, mage, paladin, voleur...) ?',
        'Première action si tu deviens maître du monde ?',
    ],
};
